# Generated by Django 5.0.6 on 2024-07-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
