# Generated by Django 5.0.6 on 2024-07-26 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_status"),
        ("users", "0003_alter_customuser_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(null=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="store.product",
                    ),
                ),
                (
                    "provider",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests_recieved",
                        to="users.sellerprofile",
                    ),
                ),
                (
                    "requester",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="users.customerprofile",
                    ),
                ),
            ],
        ),
    ]
