# Generated by Django 5.0.6 on 2024-07-26 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_status"),
        ("users", "0004_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="product",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="store.product",
            ),
        ),
    ]
