# Generated by Django 5.0.6 on 2024-07-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_request_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="price",
        ),
        migrations.AddField(
            model_name="request",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
