# Generated by Django 5.0.6 on 2024-07-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_request_price_request_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="/profile_images/no-profile-picture-icon.webp",
                null=True,
                upload_to="profile_images/",
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="/profile_images/no-profile-picture-icon.webp",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
