# Generated by Django 5.0.6 on 2024-07-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_order_payment_status_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_status",
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(default="not done", max_length=20),
        ),
    ]
