# Generated by Django 5.0.6 on 2024-07-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_remove_order_payment_status_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="product_images/istockphoto-1159447883-612x612.jpg",
                null=True,
                upload_to="product_images/",
            ),
        ),
    ]
