# Generated by Django 5.0.6 on 2024-07-06 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='posted_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to=settings.AUTH_USER_MODEL),
        ),
    ]
