# Generated by Django 5.0.6 on 2024-08-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_product_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="size",
            name="short_letter",
            field=models.CharField(default="M", max_length=1),
        ),
    ]
