# Generated by Django 5.0.6 on 2024-08-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_size_short_letter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="short_letter",
            field=models.CharField(max_length=2),
        ),
    ]
