# Generated by Django 5.0.6 on 2024-08-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_size_short_letter"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
