# Generated by Django 5.0.6 on 2024-08-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_order_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
