# Generated by Django 5.0.6 on 2024-08-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_order_created_at_order_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
