# Generated by Django 5.0.6 on 2024-08-09 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_alter_order_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="updated_at",
            new_name="order_completed_at",
        ),
    ]
