# Generated by Django 5.0.6 on 2024-07-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_cart_products_remove_cart_user_cart_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='cart', to='store.order'),
        ),
    ]
