# Generated by Django 5.0.6 on 2024-08-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_product_order_count_alter_order_cart_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="order_completed_at",
            new_name="delivered_at",
        ),
    ]
