# Generated by Django 5.0.6 on 2024-08-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_rename_order_completed_at_order_delivered_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(default="unpaid", max_length=20),
        ),
    ]
