# Generated by Django 5.0.6 on 2024-07-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_cart_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='cart_orders', to='store.order'),
        ),
    ]
