# Generated by Django 5.0.6 on 2024-08-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="product",
            field=models.ManyToManyField(blank=True, null=True, to="store.product"),
        ),
    ]
