# Generated by Django 5.0.6 on 2024-07-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_cart_orders_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart_orders', to='store.cart'),
        ),
    ]
