# Generated by Django 5.0.6 on 2024-08-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_remove_payment_order_order_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="product",
            field=models.ManyToManyField(blank=True, to="store.product"),
        ),
    ]
