# Generated by Django 5.0.6 on 2024-10-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0019_payment_delivery_price_payment_product_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="qr_code",
        ),
        migrations.AlterField(
            model_name="product",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="product_images/image15_5abf2efe-a0d2-4b34-b8fe-e3165c9f0f76.webp",
                null=True,
                upload_to="product_images/",
            ),
        ),
    ]
