# Generated by Django 5.0.6 on 2024-10-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_remove_order_qr_code_alter_product_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
